# -*- coding: utf-8 -*-
"""Elkom 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_9VMwd__qVNaHMo9Q9U_AruwByUjXMKg
"""

import pandas as pd
from google.colab import files
uploaded = files.upload()

data_quina = pd.read_csv('titanic.csv')
print(data_quina)

data1 = data_quina.loc[:,['Age','Pclass','Survived']]
print(data1)

data2 = data_quina[['Age', 'Pclass', 'Survived']]
data2.plot(title='Persebaran Data', x='Age', y='Pclass', kind='scatter', c='Survived', colormap='Paired')

data3 = data_quina[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
penumpang=data3.groupby('Pclass')['Name'].nunique()
print('Jumlah Penumpang:\n', penumpang)

#memfilter data penumpang yang selamat berdasarkan pclass
data4 = data_quina[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
notsurvivedpassanger=data4['Pclass'].loc[data_quina['Survived']==0]
print('Penumpang yang tidak survived:\n', notsurvivedpassanger.value_counts())
survivedpassanger=data4['Pclass'].loc[data_quina['Survived']==1]
print('\nPenumpang yang survived:\n', survivedpassanger.value_counts())